### ISSUE TITLE
Tokens werden nicht in Notification Center ersetzt.

### ISSUE THREAD

**Issue by wortberge** [e-spin/form-newsletter-bundle#2]
Contao Version 4.9.20
terminal42/notification_center 1.6.1
terminal42/contao-ajaxform 1.1.3
terminal42/contao-leads 1.4.20
terminal42/contao-mp_forms 4.2.2
e-spin/form-newsletter-bundler 1.0.2

in den Benachrichtigungen des NC werden die Tokens 

`##newsletter_token##
##newsletter_domain##
##newsletter_link##
##newsletter_channels##`

nicht ersetzt.

**Comment by zonky2** [comment]
hmm... muss ich gucken - ob ich nöchste Woche dazu komme, kann ich nicht versprechen.

geprüft, ob es daran liegt? https://github.com/e-spin/form-newsletter-bundle/issues/1

**Comment by wortberge** [comment]
> hmm... muss ich gucken - ob ich nöchste Woche dazu komme, kann ich nicht versprechen.
> 
> geprüft, ob es daran liegt? #1

Den Workaround habe ich angewendet. Wenn ich die Aktivierung über das Formularelement versenden lasse, bekomme ich einen funktionalen Link.

**Comment by zonky2** [comment]
ok

**Comment by zonky2** [comment]
@wortberge bitte Branch https://github.com/e-spin/form-newsletter-bundle/tree/hotfix/1.0.3 testen

**Comment by wortberge** [comment]
Die Registrierung funktioniert. Der Link ist funktional, Ziel ist die letzte Action-URL des Formulars. Das ist wohl so gewollt, oder? Die Weiterleitung wird ebenfalls korrekt ausgeführt.
An NC wird das Token anscheinend noch nicht übergeben, kann das sein?

**Comment by e-spin** [comment]
m.E. ist bei der Standardmodul der Link auch die URL wo das Modul integriert ist - oder?

NC sollte funktionieren - macht es bei mir... ggf. Cache nochmal komplett killen

**Comment by wortberge** [comment]
Bitte entschuldigt die späte Antwort. Die Tokens 

##newsletter_token##
##newsletter_domain##
##newsletter_link##
##newsletter_channels##

werden an das NC übergeben. Leider wird eine Benachrichtigung über das NC bei Newsletter-Aktivierung nicht ausgelöst.

**Comment by zonky2** [comment]
> Leider wird eine Benachrichtigung über das NC bei Newsletter-Aktivierung nicht ausgelöst.

was meinst Du damit?

**Comment by wortberge** [comment]
Im NC hat man die Möglichkeit, bei Newsletteraktionen eine Benachrichtigung auszulösen. Insbesondere bei der Aktivierung eines Abos ist das nicht uninteressant, wenn das Aufkommen der Abos so gering ist, dass ein automatisierter Sync zu einem externen Anbieter nicht gerechtfertigt ist.

<img width="596" alt="Bildschirmfoto 2022-02-21 um 10 13 20" src="https://user-images.githubusercontent.com/4026612/154924534-eea7a476-4b12-4f80-9b87-c66d747013b1.png">

**Comment by zonky2** [comment]
o.k. - dazu bitte ein eigenes Issue aufmachen - das bestehende können wir somit schließen - korrekt?

**Comment by wortberge** [comment]
> o.k. - dazu bitte ein eigenes Issue aufmachen - das bestehende können wir somit schließen - korrekt?

Alles klar, som mache ich das. Danke für die Unterstützung.
